### ISSUE TITLE
ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/dtamg-py#3]
https://github.com/transparencia-mg/new-age7/issues/85

**Comment by gabrielbdornas** [comment]
@fjuniorr, tendo em vista o fechamento do issue https://github.com/transparencia-mg/new-age7/issues/85, podemos fechar este tmb?

**Comment by fjuniorr** [comment]
A inclusão do `ruamel` no `requirements.txt` foi um _jeitinho_ pra corrigir o problema. 

Como ele é usado aqui 

https://github.com/transparencia-mg/dtamg-py/blob/64e3448feb9e40eb72b4d77cab7ab41e9fa3eb3c/dtamg_py/utils.py#L8

a gente precisa de inserir ele no fluxo de instalação normal do `dtamg-py` pra fechar esse issue.

**Comment by gabrielbdornas** [comment]
@fjuniorr, entendi bem, ou a sugestão é incluir o pacote dentro do setup.py para que ele seja instalado um pré-requisito para instalação do dtamg-py?

https://github.com/transparencia-mg/dtamg-py/blob/9c0465f04d493c74ae35b629c96e33f88474f1a7/setup.py#L9-L19

**Comment by fjuniorr** [comment]
Isso. 

Deixando um [quote](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/) relevante aqui

> install_requires is a setuptools setup.py keyword that should be used to specify what a project minimally needs to run correctly. When the project is installed by pip, this is the specification that is used to install its dependencies.

**Comment by gabrielbdornas** [comment]
@fjuniorr, pr transparencia-mg/age7#8 aberto para correção sugerida.

Observei també todos os outros pacotes estão sendo instalados com a opção `>=`:

https://github.com/transparencia-mg/dtamg-py/blob/9c0465f04d493c74ae35b629c96e33f88474f1a7/setup.py#L9-L19

Posso abrir um issue para substituir por `==`?

**Comment by fjuniorr** [comment]
> Posso abrir um issue para substituir por `==`?

Não tenho opinião formada sobre usar `>=` ou `==`.

**Comment by gabrielbdornas** [comment]
> > Posso abrir um issue para substituir por `==`?
> 
> Não tenho opinião formada sobre usar `>=` ou `==`.

@fjuniorr, vou fazer uma pesquisa aqui sobre isso, mas tendo em vista o fechamento do PR transparencia-mg/age7#8, posso fechar esse issue?

**Comment by fjuniorr** [comment]
Podemos sim
