### ISSUE TITLE
`extract_resources` deve lançar erro caso a consulta executada retorne zero linhas

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/dtamg-py#6]

**Comment by gabrielbdornas** [comment]
TODO LIST:

- [x] Fechar [PR dtamg-py](https://github.com/transparencia-mg/dtamg-py/pull/11)
- [x] Deletar branch dtamg-py
- [x] Fechar [PR age7](https://github.com/transparencia-mg/age7/pull/254)
- [x] Deletar branch age7
- [x] Conferir fechamento issue e status done projeto @work

**Comment by gabrielbdornas** [comment]
@fjuniorr, lembrar de analisar [esse do age7](https://github.com/transparencia-mg/age7/pull/254/files) também.
